export const SecureComputeFeature = () => {
  return (
    <div className="relative items-start shadow-[rgba(255,255,255,0.12)_0px_0px_0px_1px_inset,rgba(0,0,0,0.04)_0px_0px_0px_1px] box-border caret-transparent flex flex-col h-[600px] justify-end p-[21px] rounded-2xl md:p-8">
      <div className="absolute items-center box-border caret-transparent grid h-[280px] justify-items-center overflow-hidden top-px inset-x-px before:accent-auto before:bg-[linear-gradient(rgba(0,0,0,0),rgb(1,3,20))] before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-[50px] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:z-[4] before:rounded-[20px] before:border-separate before:bottom-0 before:inset-x-0 before:font-inter">
        <div className="relative bg-[linear-gradient(rgba(48,39,85,0.8)_0%,rgba(10,6,34,0.8)_100%)] shadow-[rgb(33,26,64)_0px_0px_100px_0px,rgba(0,0,0,0.8)_0px_8px_16px_-4px,rgba(0,0,0,0.5)_0px_4px_8px_-2px,rgba(0,0,0,0.9)_0px_1px_2px_0px,rgba(190,167,255,0.24)_0px_0px_0px_1px_inset] box-border caret-transparent h-[150px] w-[150px] rounded-[50%] before:accent-auto before:bg-[linear-gradient(rgba(190,167,255,0.14),rgb(190,167,255))] before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_1px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-0.5 before:rounded-[50%] before:border-separate before:-top-3 before:font-inter">
          <div className="box-border caret-transparent h-full w-full">
            <div className="absolute bg-[linear-gradient(rgba(48,39,85,0.8)_0%,rgba(10,6,34,0.8)_100%)] shadow-[rgb(33,26,64)_0px_0px_100px_0px,rgba(0,0,0,0.25)_0px_8px_16px_-4px,rgba(0,0,0,0.25)_0px_4px_8px_-2px,rgba(0,0,0,0.2)_0px_1px_2px_0px,rgba(190,167,255,0.24)_0px_0px_0px_1px_inset] box-border caret-transparent h-[60px] left-[calc(50%_-_30px)] top-[calc(50%_-_30px)] w-[60px] rounded-[50%] before:accent-auto before:bg-[linear-gradient(rgba(255,255,255,0)_20%,rgba(255,255,255,0.25))] before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_4px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-2 before:rounded-[50%] before:border-separate before:top-2 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] w-3 before:accent-auto before:bg-slate-500 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter">
              <div className="absolute text-violet-400 text-[9px] box-border caret-transparent leading-[13.95px] text-center top-3.5 inset-x-0">
                0
              </div>
            </div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[3.599997906246242deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[7.199984578398026deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[10.799984986686324deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[14.400008557772217deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[17.99999174234843deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[21.600034077858574deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[25.199986164383496deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[28.80000753134356deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[32.40000763104835deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[35.9999881159815deg] w-3 before:accent-auto before:bg-slate-500 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter">
              <div className="absolute text-violet-400 text-[9px] box-border caret-transparent leading-[13.95px] text-center top-3.5 inset-x-0">
                10
              </div>
            </div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[39.60000931915349deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[43.199980962547976deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[46.80001903745203deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[50.399990680846514deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[54.00001188401849deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[57.59999236895165deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[61.19999246865644deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[64.80001383561651deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[68.39996592214143deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[72.00000825765157deg] w-3 before:accent-auto before:bg-slate-500 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter">
              <div className="absolute text-violet-400 text-[9px] box-border caret-transparent leading-[13.95px] text-center top-3.5 inset-x-0">
                20
              </div>
            </div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[75.59999144222778deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[79.20001501331369deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[82.80001542160197deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[86.40000209375376deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-90 w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[93.59999790624624deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[97.19998457839803deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[100.79998498668633deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[104.40000855777224deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[107.99999174234844deg] w-3 before:accent-auto before:bg-slate-500 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter">
              <div className="absolute text-violet-400 text-[9px] box-border caret-transparent leading-[13.95px] text-center top-3.5 inset-x-0">
                30
              </div>
            </div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[111.60003407785858deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[115.19998616438347deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[118.80000753134357deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[122.40000763104835deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[125.99998811598151deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[129.6000093191535deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[133.19998096254798deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[136.80001903745202deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[140.3999906808465deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[144.0000118840185deg] w-3 before:accent-auto before:bg-slate-500 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter">
              <div className="absolute text-violet-400 text-[9px] box-border caret-transparent leading-[13.95px] text-center top-3.5 inset-x-0">
                40
              </div>
            </div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[147.59999236895166deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[151.19999246865643deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[154.8000138356165deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[158.39996592214143deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[162.0000082576516deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[165.59999144222778deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[169.20001501331367deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[172.80001542160196deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[176.40000209375378deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] w-3 -scale-100 before:accent-auto before:bg-slate-500 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter">
              <div className="absolute text-violet-400 text-[9px] box-border caret-transparent leading-[13.95px] text-center top-3.5 inset-x-0">
                50
              </div>
            </div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-176.40000209375378deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-172.80001542160196deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-169.20001501331367deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-165.59999144222778deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-162.0000082576516deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-158.39996592214143deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-154.8000138356165deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-151.19999246865643deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-147.59999236895166deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-144.0000118840185deg] w-3 before:accent-auto before:bg-slate-500 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter">
              <div className="absolute text-violet-400 text-[9px] box-border caret-transparent leading-[13.95px] text-center top-3.5 inset-x-0">
                60
              </div>
            </div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-140.3999906808465deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-136.80001903745202deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-133.19998096254798deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-129.6000093191535deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-125.99998811598151deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-122.40000763104835deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-118.80000753134357deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-115.19998616438347deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-111.60003407785858deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-107.99999174234844deg] w-3 before:accent-auto before:bg-slate-500 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter">
              <div className="absolute text-violet-400 text-[9px] box-border caret-transparent leading-[13.95px] text-center top-3.5 inset-x-0">
                70
              </div>
            </div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-104.40000855777224deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-100.79998498668633deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-97.19998457839803deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-93.59999790624624deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] -rotate-90 w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-86.40000209375376deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-82.80001542160197deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-79.20001501331369deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-75.59999144222778deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-72.00000825765157deg] w-3 before:accent-auto before:bg-slate-500 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter">
              <div className="absolute text-violet-400 text-[9px] box-border caret-transparent leading-[13.95px] text-center top-3.5 inset-x-0">
                80
              </div>
            </div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-68.39996592214143deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-64.80001383561651deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-61.19999246865644deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-57.59999236895165deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-54.00001188401849deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-50.399990680846514deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-46.80001903745203deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-43.199980962547976deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-39.60000931915349deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-35.9999881159815deg] w-3 before:accent-auto before:bg-slate-500 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter">
              <div className="absolute text-violet-400 text-[9px] box-border caret-transparent leading-[13.95px] text-center top-3.5 inset-x-0">
                90
              </div>
            </div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-32.40000763104835deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-28.80000753134356deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-25.199986164383496deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-21.600034077858574deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-17.99999174234843deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-2 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-14.400008557772217deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-10.799984986686324deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-7.199984578398026deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
            <div className="absolute box-border caret-transparent h-[150px] left-[calc(50%_-_6px)] top-[calc(50%_-_75px)] rotate-[-3.599997906246242deg] w-3 before:accent-auto before:bg-indigo-900 before:box-border before:caret-transparent before:text-slate-200 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-1 before:left-[calc(50%_-_0.5px)] before:tracking-[normal] before:leading-[24.8px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-px before:border-separate before:top-1 before:font-inter"></div>
          </div>
        </div>
      </div>
      <h4 className="text-purple-400 text-[11.2px] font-medium box-border caret-transparent leading-[11.2px] mb-[8.4px] font-roobert md:text-[12.8px] md:leading-[12.8px] md:mb-[9.6px]">
        Computing for highly sensitive payment operations
      </h4>
      <h3 className="text-white text-[21px] font-medium box-border caret-transparent leading-[26.25px] mb-[15.75px] font-roobert md:text-2xl md:leading-[30px] md:mb-[18px]">
        Easily prove to enterprise customers that their data is handled with
        maximum security.
      </h3>
      <p className="text-[12.6px] box-border caret-transparent leading-[24.5px] mb-7 md:text-[14.4px] md:leading-7 md:mb-8">
        Evervault makes it easy for developers to run sensitive payment
        workloads in highly-constrained compute environments using secure
        enclaves.
      </p>
      <a
        href="/primitives/enclaves"
        className="text-purple-400 text-[12.6px] font-medium items-center box-border caret-transparent flex leading-[19.53px] underline-offset-[3px] z-[3] md:text-[14.4px] md:leading-[22.32px]"
      >
        Learn more
        <img
          src="https://c.animaapp.com/mjeo1lfi7UPOYs/assets/icon-22.svg"
          alt="Icon"
          className="text-[12.6px] box-border caret-transparent h-2.5 leading-[19.53px] w-2.5 ml-[5.04px] md:text-[14.4px] md:leading-[22.32px] md:ml-[5.76px]"
        />
      </a>
    </div>
  );
};
